/* eslint-disable */
/**
 * Generated by convex — stub for build compatibility.
 * Real generated file will be created by `npx convex dev`.
 *
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

import type * as users from "../users.js";
import type * as dashboard from "../dashboard.js";
import type * as dgss from "../dgss.js";
import type * as secretariat from "../secretariat.js";
import type * as operations from "../operations.js";
import type * as seed from "../seed.js";

/**
 * A utility for referencing Convex functions in your app's API.
 */
declare const fullApi: ApiFromModules<{
  users: typeof users;
  dashboard: typeof dashboard;
  dgss: typeof dgss;
  secretariat: typeof secretariat;
  operations: typeof operations;
  seed: typeof seed;
}>;

export declare const api: FilterApi<typeof fullApi, FunctionReference<any, "public">>;
export declare const internal: FilterApi<typeof fullApi, FunctionReference<any, "internal">>;
