/* eslint-disable */
/**
 * Generated by convex — stub for build compatibility.
 */

import type {
  GenericQueryCtx,
  GenericMutationCtx,
  GenericActionCtx,
  FunctionReference,
  DataModelFromSchemaDefinition,
} from "convex/server";
import type schema from "../schema.js";

export type DataModel = DataModelFromSchemaDefinition<typeof schema>;

export declare const query: any;
export declare const internalQuery: any;
export declare const mutation: any;
export declare const internalMutation: any;
export declare const action: any;
export declare const internalAction: any;
export declare const httpAction: any;
