/* eslint-disable */
/**
 * Generated by convex — stub for build compatibility.
 */

export {
  actionGeneric,
  httpActionGeneric,
  queryGeneric,
  mutationGeneric,
  internalActionGeneric,
  internalMutationGeneric,
  internalQueryGeneric,
} from "convex/server";

import type { DataModelFromSchemaDefinition } from "convex/server";
import type schema from "../schema.js";

export type DataModel = DataModelFromSchemaDefinition<typeof schema>;

export const query = queryGeneric as any;
export const mutation = mutationGeneric as any;
export const action = actionGeneric as any;
export const internalQuery = internalQueryGeneric as any;
export const internalMutation = internalMutationGeneric as any;
export const internalAction = internalActionGeneric as any;
export const httpAction = httpActionGeneric as any;

import {
  queryGeneric,
  mutationGeneric,
  actionGeneric,
  internalQueryGeneric,
  internalMutationGeneric,
  internalActionGeneric,
  httpActionGeneric,
} from "convex/server";
